from __future__ import annotations
from typing import Any, Dict, List, Optional

def build_initial_state(
    *,
    question: str,
    file_id: str = "",
    files: Optional[List[Dict[str, Any]]] = None,
    task_id: str = "",
    run_mode: str = "sync",
    resumed_from: Optional[str] = None,
) -> Dict[str, Any]:
    return {
        "question": question,
        "file_id": file_id or "",
        "files": list(files or []),
        "plan": {},
        "steps": [],
        "task": {},
        "task_id": task_id or "",
        "run_mode": run_mode or "sync",
        "resumed_from": resumed_from or "",
        "cancel_requested": False,
        "current_step_index": 0,
        "step_results": [],
        "final_answer": "",
        "tool_results_v2": [],
        "execution_trace": [],
        "artifacts": [],
        "sources": [],
        "context_score": 0.0,
        "force_tool": None,
        "need_kb": False,
        "trace": [],
        "error": "",
        "replanning_needed": False,
        "answer_revision_needed": False,
        "review_count": 0,
        "feedback": "",
        "is_satisfactory": True,
        "retrieval_quality_score": 0.0,
        "retrieval_quality_detail": {},
        "retrieval_chunks": [],
        "execution_replan_count": 0,
        "answer_confidence_score": 0.0,
        "answer_confidence_label": "",
        "remediation_count": 0,
        "remediation_stats": {
            "tool_failure_streak": {},
            "issue_counts": {},
            "step_remediation_counts": {},
            "llm_empty_retry_count": 0,
        },
        "unresolved_outcomes": [],
        "remediation_metrics": {},
        "evidence_quality_assessment": {},
        "active_step_results": [],
        "active_tool_results_v2": [],
        "active_execution_trace": [],
        "active_artifacts": [],
        "active_sources": [],
        "active_retrieval_chunks": [],
    }
